import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Component/MenuBar/menu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{backgroundColor: '#f5f5f4', color: '#27272a'}}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
